---
title: "Bachelor analysis"
author: "Maria"
date: "28/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
```

Packages

```{r}
#load packages
pacman::p_load(tidyverse, lme4, lmerTest)

```

Load data

```{r}
#read experimental data (run in one go)
setwd("C:/Users/maria/OneDrive/Dokumenter/Uni/Bachelor/Bachelor Analysis/Test-data-til-bachelor")

pavlovia <- list.files(path = "C:/Users/maria/OneDrive/Dokumenter/Uni/Bachelor/Bachelor Analysis/Test-data-til-bachelor",  
                       pattern = "*.csv") %>% 
  map_df(~read_csv(.))


#read survey data
qual <- read_csv("B21-HC full_November 5, 2021_02.11.csv")  

# qual <- read.csv("spørgeskema.csv", fileEncoding = "UTF-8", na.strings = c("", "NA")) %>% 
#   subset(EndDate != " ") #remove ourselves?

```
Fix the same IDs

```{r}
#check to see if participants have the same id
qual %>%
  group_by(id) %>%
  dplyr::summarise(Count = n()) 

#16727 -
#8024 -
#8083 -
#1349


#separate participants with the same randomly generated ID (16727)
id_16727_1 <- pavlovia %>% 
  filter(id == "16727") %>% 
  filter(date == "2021-11-04_16h06.00.374") %>% 
  mutate(id = ifelse(id == 16727, 111111, NA)) #give new id

id_16727_2 <- pavlovia %>% 
  filter(id == "16727") %>% 
  filter(date == "2021-10-13_15h58.51.979") %>% 
  mutate(id = ifelse(id == 16727, 222222, NA)) #give new id

#next participant 8024
id_8024_1 <- pavlovia %>% 
  filter(id == "8024") %>% 
  filter(date == "2021-10-29_07h55.44.902") %>% 
  mutate(id = ifelse(id == 8024, 333333, NA)) #give new id

id_8024_2 <- pavlovia %>% 
  filter(id == "8024") %>% 
  filter(date == "2021-10-25_15h47.07.921") %>% 
  mutate(id = ifelse(id == 8024, 444444, NA)) #give new id


#filter out 16727 from main dataframe
pavlovia <- pavlovia %>% 
  filter(id != 16727) %>% 
  filter(id != 8024)

#rowbind the data to add the participants again
pavlovia <- rbind(pavlovia, id_16727_1)
pavlovia <- rbind(pavlovia, id_16727_2)
pavlovia <- rbind(pavlovia, id_8024_2)
pavlovia <- rbind(pavlovia, id_8024_1)


#----------
#again separate participants with the same randomly generated ID 
qual16727_1 <- qual %>% 
  filter(id == "16727") %>% 
  filter(RecordedDate == "2021-11-04 09:35:31") %>% 
  mutate(id = ifelse(id == 16727, 111111, NA)) #give new id

qual16727_2 <- qual %>% 
  filter(id == "16727") %>% 
  filter(RecordedDate == "2021-10-13 08:19:03") %>% 
  mutate(id = ifelse(id == 16727, 222222, NA)) #give new id

#8024
qual8024_1 <- qual %>% 
  filter(id == "8024") %>% 
  filter(RecordedDate == "2021-10-29 00:59:32") %>% 
  mutate(id = ifelse(id == 8024, 333333, NA)) #give new id

qual8024_2 <- qual %>% 
  filter(id == "8024") %>% 
  filter(RecordedDate == "2021-10-25 08:34:42") %>% 
  mutate(id = ifelse(id == 8024, 444444, NA)) #give new id

#filter out participant from survey dataframe
qual <- qual %>% 
  filter(id != "16727") %>% 
  filter(id != "8024")

#rowbind the data to add the participants again
qual <- rbind(qual, qual16727_1)
qual <- rbind(qual, qual16727_2)
qual <- rbind(qual, qual8024_1)
qual <- rbind(qual, qual8024_2)


```

Merge data

```{r}
#merge pavlovia and survey
merged <- merge(pavlovia, qual)

#write_csv(merged, "merged.csv")

#filter out
merged <- filter(merged, !EndDate == "2021-10-05 07:12:27")

```

Clean dataframe

```{r}
#read full dataframe
df <- merged %>% 
  filter(anagrams != "remove" | is.na(anagrams)) #remove false anagrams but keep trials without anagrams

#remove participants and trials based on exclusion criteria and errors
df <- subset(df, !is.na(df$RT)) %>% #remove missing reaction times
  subset(Att_disease != "Ja") %>% #remove attentional disorders
  subset(Pregnant != "Ja") %>% #remove recent pregnancy 
  subset(Hormonal_disease != "Ja") %>% #remove hormonal diseases
  subset(HC_time != "Under 3 måneder") %>% 
  subset(Age_1 < 40) %>% 
  subset(Gender != "Mand")

#keep only relevant columns
df <- subset(df, select = c(id, anagram_answer, RT, anagrams, correct, IQresponse.keys, IQresponse.corr, options, CorrectIQ, Gender, Age_1, HC_use, HC_ever, HC_time, Time_since_use, Previous_HC_Time, HC_type, HC_type_8_TEXT, Brand, Generation, Pregnant, Hormonal_disease, Days_since_last_mens, Length_of_cycle, Prediction_ability_1, Att_disease, Dyslexic, Education, IQ_abilities_1, IQ_abilities_2, IQ_abilities_3, Difficulty_1, Difficulty_2, Social_setting, Height_1, Weight_1, OC_cycle, IUD, IUD_time_1, previous_HC, previous_HC_type, why_change_HC, Previous_HC_cancel, HC_sideeffects, Sexuality, Sexual_orientation, Partner, Children, Psych_comorbidity, Medication_depress, Medication_anxiety, Smoking, Alcohol_use, Alcohol_weekly, Alcohol_craving_1, Alcohol_crav_1, Alcohol_crav_2, Alcohol_crav_3, Alcohol_crav_4, Alcohol_crav_5, Alcohol_crav_6, Alcohol_crav_7, Alcohol_crav_8, Alcohol_crav_9, Alcohol_crav_10, Alcohol_crav_11, Alcohol_crav_12, Alcohol_audit1, Alcohol_audit2,Alcohol_audit3, Alcohol_audit4,Alcohol_audit5,Alcohol_audit6,Alcohol_audit7,Alcohol_audit8,Alcohol_audit9,Alcohol_audit10)) #tror det er det hele

```

Make column for accuracy 

```{r}
#code accuracy column for both tasks
df <- df %>% 
  mutate(anagram_answer = ifelse(is.na(anagram_answer), "wrong", anagram_answer)) %>% #NAs count as wrong answers
  mutate(anagram_accuracy = ifelse(anagram_answer == correct, 1, 0)) %>% #1 for correct solutions, 0 for incorrect (referring to correct column)
  mutate(anagram_accuracy = ifelse(anagram_answer == "demoshow", 1, anagram_accuracy)) %>% #accept this as correct
  mutate(overall_accuracy = anagram_accuracy) %>% #copy the anagram accuracy to the overall accuracy
  mutate(overall_accuracy = ifelse(is.na(overall_accuracy), IQresponse.corr, anagram_accuracy)) %>% #add the IQ accuracy where we have missing info 
  mutate(overall_accuracy = ifelse(is.na(overall_accuracy), 0, overall_accuracy))


```

Make column for menstrual cycle

```{r}
#fix class
df <- df %>% 
  mutate(Days_since_last_mens = as.numeric(Days_since_last_mens)) %>% #numeric
  mutate(Length_of_cycle = as.numeric(Length_of_cycle)) #numeric
         
#calculate percentage and menstrual phases (rough estimate)
df <- df %>% 
  mutate(Percentage_cycle = (Days_since_last_mens/Length_of_cycle)*100) %>% #how far along in menstrual cycle
  mutate(Menstrual_phase = ifelse(Percentage_cycle >= 0 & Percentage_cycle <= 45, "follicular phase", NA)) %>%  #follicular phase
  mutate(Menstrual_phase = ifelse(Percentage_cycle > 45 & Percentage_cycle <= 55, "ovulation", Menstrual_phase)) %>%  #ovulation 
  mutate(Menstrual_phase = ifelse(Percentage_cycle > 55, "luteal phase", Menstrual_phase)) %>%  #luteal phase
  mutate(Menstrual_phase = ifelse(is.na(Menstrual_phase), "hormonal group", Menstrual_phase)) #add the hormonal group to avoid NAs

```

Make column for task type

```{r}
df <- df %>% 
  mutate(Task = ifelse(is.na(anagram_accuracy), "IQ", "anagram")) %>%  #make task column
  mutate(Dyslexic = ifelse(Dyslexic == "Ja" & Task == "anagram", "remove", Dyslexic)) %>%  #remove dyslecix people in anagram tasks
  filter(Dyslexic != "remove")
  
```

Fix spelling 
```{r}
#correcting spelling mistakes etc in the brand column
merged$Brand[merged$Brand == "2"] <- NA
merged$Brand[merged$Brand == "2 gen"] <- NA
merged$Brand[merged$Brand == "2 generation"] <- NA
merged$Brand[merged$Brand == "2."] <- NA
merged$Brand[merged$Brand == "2. generation"] <- NA
merged$Brand[merged$Brand == "2 generation Malonetta"] <- "Malonetta"
merged$Brand[merged$Brand == "2. generations - Microgyn"] <- "Microgyn"
merged$Brand[merged$Brand == "2. generations p-piller (femicept)"] <- "Femicept"
merged$Brand[merged$Brand == "2. Generations, Microgyn (Stoppede på p-piller for 6 år siden))"] <- "Microgyn"
merged$Brand[merged$Brand == "2. genration Femicept"] <- "Femicept"

merged$Brand[merged$Brand == "3. generation"] <- NA
merged$Brand[merged$Brand == "Anastella"] <- "Anastrella"
merged$Brand[merged$Brand == "anastrella"] <- "Anastrella"
merged$Brand[merged$Brand == "femicept"] <- "Femicept"
merged$Brand[merged$Brand == "cilest"] <- "Cilest"

merged$Brand[merged$Brand == "Det er over 10 år siden
"] <- NA
merged$Brand[merged$Brand == "Femicept, Mirabella (2. generation)
"] <- "Femicept"
merged$Brand[merged$Brand == "fik altid de billigste. ved ikke hvilket mærke det er flere år siden
"] <- NA
merged$Brand[merged$Brand == "Gestinyl lyder bekendt (mere end 4 år siden)
"] <- NA
merged$Brand[merged$Brand == "leverette"] <- "Leverette 21"
merged$Brand[merged$Brand == "Leverette 21 (indeholder levonorgestrel./ethinylestradiol
"] <- "Leverette 21"
merged$Brand[merged$Brand == "Leverette 21 Ethinylestr + Levonorgest"] <- "Leverette 21"

merged$Brand[merged$Brand == "malonetta"] <- "Malonetta"
merged$Brand[merged$Brand == "Malonetta, 2. generations"] <- "Malonetta"
merged$Brand[merged$Brand == "melonetta"] <- "Malonetta"
merged$Brand[merged$Brand == "2. generation Malonetta"] <- "Malonetta"
```


Shorten answers

```{r}


#shorten education names
df <- df %>% 
  mutate(Education = ifelse(Education == "Kort videregående uddannelse (fx erhvervsuddannelse på 2 år inkl praktik)", "Kort", Education)) %>% 
  mutate(Education = ifelse(Education == "Mellemlang videregående uddannelse (fx bachelor)", "Mellemlang", Education)) %>% 
  mutate(Education = ifelse(Education == "Lang videregående uddannelse (fx kandidat el. PhD)", "Lang", Education)) %>% 
  mutate(Education = ifelse(Education == "Anden uddannelse (under 2 år)", "Anden kort", Education)) %>% 
  mutate(Education = as.factor(Education))

#shorten answers
df <- df %>% 
  mutate(Social_setting = ifelse(Social_setting == "Nej, jeg sad alene og løste opgaverne", "Nej", "Ja")) %>% 
  mutate(OC_cycle = ifelse(OC_cycle == "Ja, jeg har taget eller skal tage min p-pille i dag", "Aktiv pille-dag", OC_cycle)) %>% 
  mutate(OC_cycle = ifelse(OC_cycle == "Nej, jeg holder pause mellem to pakker lige nu", "Pause", OC_cycle)) %>% 
  mutate(OC_cycle = ifelse(OC_cycle == "Jeg er for nyligt helt stoppet på p-piller", "Pause", OC_cycle)) #feedback fra personen sagde at de lige var stoppet sidste uge

```

Define lower + upper limit and round RT

```{r}
df <- df %>% 
  mutate(RT = round(RT, digits = 2)) %>% 
  #mutate(AVG_IQ_Ability = round(AVG_IQ_Ability, digits = 2)) %>% 
  subset(RT >= 1) %>% #exclude unrealistic response times
  mutate(RT = ifelse(RT >= 600, 600, RT)) #define an upper limit of 10 minutes 
  
```


Summarize Participants

```{r}
#summarizing stats
merged %>%
  group_by(HC_use) %>%
  dplyr::summarise(participants = length(unique(id)))
#started out with xx participants, of whom xx were on HC and xx were not. 

merged %>%
  group_by(Att_disease) %>%
  dplyr::summarise(participants = length(unique(id)))
#xx sorted out bcs of ADHD etc

merged %>%
  group_by(Hormonal_disease) %>%
  dplyr::summarise(participants = length(unique(id)))
#xx sorted out bcs of hormonal diseases

merged %>%
  group_by(Pregnant) %>%
  dplyr::summarise(participants = length(unique(id)))
#xx sorted out due to either pregnancy or breastfeeding

merged %>%
  group_by(Dyslexic, HC_use) %>%
  dplyr::summarise(participants = length(unique(id)))
#xx sorted out due to either pregnancy or breastfeeding

#check to see if participants have the same id
df %>%
  group_by(id) %>%
  dplyr::summarise(Count = n()) 


```

Distribution check


```{r}
#density distributions for time and accuracy 
dens(df$RT) #log-normal?
dens(df$overall_accuracy) #binomial?

```

Fix classes and relevel

```{r}

class(df$HC_use)
levels(df$HC_use)

#fix classes
df <- df %>% 
  mutate(HC_use = as.factor(HC_use)) %>% #make into factor
  mutate(HC_type = as.factor(HC_type)) %>% #make into factor
  mutate(Task = as.factor(Task))  #make into factor


#fix education levels
df$Education <- factor(df$Education, levels = c("Folkeskole", "Gymnasiel uddannelse", "Anden kort", "Kort", "Mellemlang", "Lang"))

#fix HC levels
df$HC_use <- factor(df$HC_use, levels = c("Nej", "Ja"))


```

Modelling

```{r}
#syntax test
accuracy_m <- glmer(overall_accuracy ~ HC_use + (1 | Menstrual_phase:id ), data = df, family=binomial)

RT_m <- lmerTest::lmer(RT ~ HC_use + Menstrual_phase + (1 | Menstrual_phase:id), data = df) 

#lognormal family apparently not an option in the family argument ??? kan være vi bare skal logtransformere inden og så køre almindelig gaussian 
# https://stats.stackexchange.com/questions/21447/how-to-specify-a-lognormal-distribution-in-the-glm-family-argument-in-r

# binomial(link = "logit")
# gaussian(link = "identity")
# Gamma(link = "inverse")
# inverse.gaussian(link = "1/mu^2")
# poisson(link = "log")
# quasi(link = "identity", variance = "constant")
# quasibinomial(link = "logit")
# quasipoisson(link = "log")

```















